FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["SiteMonitoring/SiteMonitoring.csproj", "SiteMonitoring/"]
COPY ["Core/Core.DatabaseRepository/Core.DatabaseRepository.csproj", "Core/Core.DatabaseRepository/"]
COPY ["Core/Common.DbSessionFactory/Common.DbSessionFactory.csproj", "Core/Common.DbSessionFactory/"]
COPY ["Orm/Mapping/Mapping.csproj", "Orm/Mapping/"]
COPY ["Orm/Model/Model.csproj", "Orm/Model/"]
RUN dotnet restore "SiteMonitoring/SiteMonitoring.csproj"
COPY . .
WORKDIR "/src/SiteMonitoring"
RUN dotnet build "SiteMonitoring.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SiteMonitoring.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SiteMonitoring.dll"]